### PR TITLE
added dockerfile

### PR DESCRIPTION
**Pull request by faddat**

### CODE REVIEW

**Comment by faddat** [comment]
Alex, can you check if it blends for me?  Just... do your ruby magic on 
it and give me a thumbs up or down?  It should be able to connect to the 
existing DB...

-Jake

**Comment by undergroundwebdesigns** [comment]
Wait, I'm confused. Why is the dockerfile running config/application.rb... and where is it defining a DB? I'm not a Ruby expert, but it looks like that dockerfile is running Ruby only, no? Will DB credentials be in an ENV variable or something?

**Comment by faddat** [comment]
Yes, creds will go into an evn var, you got it sir.

**Comment by faddat** [comment]
also, if it shouldn't run config/application.rb..... can you tell me how it would normally work?  I know precisely jack shit about Ruby...

**Pull request merged**
